# reference: https://github.com/openai/codex/blob/main/docs/config.md#config-reference

model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

model_provider = "openai"

preferred_auth_method = "chatgpt"

sandbox_mode = "workspace-write"
approval_policy = "on-request"

web_search = "live"
personality = "pragmatic"

[features]
unified_exec = true
collab = true
collaboration_modes = true

[sandbox_workspace_write]
network_access = true

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]
enabled = true

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
enabled = true


[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"
enabled = true


[mcp_servers.aws_knowledge]
url = "https://knowledge-mcp.global.api.aws"
enabled = true
