# reference: https://github.com/openai/codex/blob/main/docs/config.md#config-reference

model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"

model_provider = "openai"

preferred_auth_method = "chatgpt"

sandbox_mode = "workspace-write"
approval_policy = "on-request"

[feature]
web_search_request = true

[sandbox_workspace_write]
network_access = true

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.context7.com/mcp"]

[mcp_servers.deepwiki]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.deepwiki.com/mcp"]

[notice]
hide_gpt5_1_migration_prompt = true
hide_gpt-5.1-codex-max_migration_prompt = true
